### ISSUE TITLE
Performance Improvement

### ISSUE THREAD

**Issue by HollowaySean** [HollowaySean/BasilGL#106]
* [ ] Reduce heap allocations
* [ ] Benchmark performance
* [ ] Create automated benchmarks
* [ ] First pass of performance improvement
