### ISSUE TITLE
Onboard to GitHub Issues

### ISSUE THREAD

**Issue by HollowaySean** [HollowaySean/BasilGL#20]
Acceptance criteria:
* [x] Define P0 criteria in GitHub Issues 
* [x] Transfer old README action items to GitHub Issues
* [x] Transfer old Kanban action items to GitHub Issues
* [x] Try out GitHub Projects
