### ISSUE TITLE
Testing improvements

### ISSUE THREAD

**Issue by HollowaySean** [HollowaySean/BasilGL#25]
Acceptance criteria:
* [ ] Separate tests into independent suites
* [ ] Create render tests
* [ ] Run profiler on simple example
