### ISSUE TITLE
Uncategorized future feature ideas

### ISSUE THREAD

**Issue by HollowaySean** [HollowaySean/BasilGL#31]
Tracking issue for idea backlog
* Build system
  * [ ] Distribution from package manager
  * [ ] Emscripten support
* Features
  * [ ] Compute shader support
  * [ ] Video output system
