### ISSUE TITLE
Example projects

### ISSUE THREAD

**Issue by HollowaySean** [HollowaySean/BasilGL#33]
* [ ] Simple shadertoy
* [ ] Simple ray tracer
* [ ] Fluid simulator re-implementation
* [ ] Fluid simulator improvement
* [ ] Black hole project re-implementation
